# System Clock (50 MHz PL Clock -> Pin N18)
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports clk]
create_clock -period 20.000 -name sys_clk_pin -waveform {0.000 10.000} -add [get_ports clk]

# Reset / User Key (PL KEY1 -> Pin N15)
#set_property -dict { PACKAGE_PIN N15   IOSTANDARD LVCMOS33 } [get_ports { rst }];

# Alternative Reset Key (PL KEY2 -> Pin P16)
set_property -dict {PACKAGE_PIN P16 IOSTANDARD LVCMOS33} [get_ports rst_n]

# User LEDs (PL_LED1 -> M14, PL_LED2 -> M15)
set_property -dict {PACKAGE_PIN M15 IOSTANDARD LVCMOS33} [get_ports {leds[0]}]
set_property -dict {PACKAGE_PIN U12 IOSTANDARD LVCMOS33} [get_ports {leds[1]}]

create_pblock pblock_1
add_cells_to_pblock [get_pblocks pblock_1] [get_cells -quiet [list \
          dut/GND \
          dut/m_alu_i_1 \
          dut/m_alu_i_10 \
          dut/m_alu_i_11 \
          dut/m_alu_i_12 \
          dut/m_alu_i_13 \
          dut/m_alu_i_14 \
          dut/m_alu_i_15 \
          dut/m_alu_i_16 \
          dut/m_alu_i_17 \
          dut/m_alu_i_18 \
          dut/m_alu_i_19 \
          dut/m_alu_i_2 \
          dut/m_alu_i_20 \
          dut/m_alu_i_21 \
          dut/m_alu_i_22 \
          dut/m_alu_i_23 \
          dut/m_alu_i_24 \
          dut/m_alu_i_25 \
          dut/m_alu_i_26 \
          dut/m_alu_i_27 \
          dut/m_alu_i_28 \
          dut/m_alu_i_29 \
          dut/m_alu_i_3 \
          dut/m_alu_i_30 \
          dut/m_alu_i_31 \
          dut/m_alu_i_32 \
          dut/m_alu_i_33 \
          dut/m_alu_i_34 \
          dut/m_alu_i_35 \
          dut/m_alu_i_36 \
          dut/m_alu_i_37 \
          dut/m_alu_i_38 \
          dut/m_alu_i_39 \
          dut/m_alu_i_4 \
          dut/m_alu_i_40 \
          dut/m_alu_i_41 \
          dut/m_alu_i_42 \
          dut/m_alu_i_43 \
          dut/m_alu_i_44 \
          dut/m_alu_i_45 \
          dut/m_alu_i_46 \
          dut/m_alu_i_47 \
          dut/m_alu_i_48 \
          dut/m_alu_i_49 \
          dut/m_alu_i_5 \
          dut/m_alu_i_50 \
          dut/m_alu_i_51 \
          dut/m_alu_i_52 \
          dut/m_alu_i_53 \
          dut/m_alu_i_54 \
          dut/m_alu_i_55 \
          dut/m_alu_i_56 \
          dut/m_alu_i_57 \
          dut/m_alu_i_58 \
          dut/m_alu_i_59 \
          dut/m_alu_i_6 \
          dut/m_alu_i_60 \
          dut/m_alu_i_61 \
          dut/m_alu_i_62 \
          dut/m_alu_i_63 \
          dut/m_alu_i_64 \
          dut/m_alu_i_65 \
          dut/m_alu_i_7 \
          dut/m_alu_i_8 \
          dut/m_alu_i_9 \
          dut/u_data_mem_i_1 \
          dut/u_data_mem_i_2 \
          dut/u_data_mem_i_3 \
          dut/u_data_mem_i_4 \
          dut/u_pc_i_1 \
          dut/u_pc_i_10 \
          dut/u_pc_i_100 \
          dut/u_pc_i_101 \
          dut/u_pc_i_102 \
          dut/u_pc_i_103 \
          dut/u_pc_i_104 \
          dut/u_pc_i_105 \
          dut/u_pc_i_106 \
          dut/u_pc_i_107 \
          dut/u_pc_i_108 \
          dut/u_pc_i_109 \
          dut/u_pc_i_11 \
          dut/u_pc_i_110 \
          dut/u_pc_i_111 \
          dut/u_pc_i_112 \
          dut/u_pc_i_113 \
          dut/u_pc_i_114 \
          dut/u_pc_i_115 \
          dut/u_pc_i_116 \
          dut/u_pc_i_117 \
          dut/u_pc_i_118 \
          dut/u_pc_i_119 \
          dut/u_pc_i_12 \
          dut/u_pc_i_120 \
          dut/u_pc_i_121 \
          dut/u_pc_i_122 \
          dut/u_pc_i_123 \
          dut/u_pc_i_124 \
          dut/u_pc_i_125 \
          dut/u_pc_i_126 \
          dut/u_pc_i_13 \
          dut/u_pc_i_14 \
          dut/u_pc_i_15 \
          dut/u_pc_i_16 \
          dut/u_pc_i_17 \
          dut/u_pc_i_18 \
          dut/u_pc_i_19 \
          dut/u_pc_i_2 \
          dut/u_pc_i_20 \
          dut/u_pc_i_21 \
          dut/u_pc_i_22 \
          dut/u_pc_i_23 \
          dut/u_pc_i_24 \
          dut/u_pc_i_25 \
          dut/u_pc_i_26 \
          dut/u_pc_i_27 \
          dut/u_pc_i_28 \
          dut/u_pc_i_29 \
          dut/u_pc_i_3 \
          dut/u_pc_i_30 \
          dut/u_pc_i_31 \
          dut/u_pc_i_32 \
          dut/u_pc_i_33 \
          dut/u_pc_i_34 \
          dut/u_pc_i_35 \
          dut/u_pc_i_36 \
          dut/u_pc_i_37 \
          dut/u_pc_i_38 \
          dut/u_pc_i_39 \
          dut/u_pc_i_4 \
          dut/u_pc_i_40 \
          dut/u_pc_i_41 \
          dut/u_pc_i_42 \
          dut/u_pc_i_43 \
          dut/u_pc_i_44 \
          dut/u_pc_i_45 \
          dut/u_pc_i_46 \
          dut/u_pc_i_47 \
          dut/u_pc_i_48 \
          dut/u_pc_i_49 \
          dut/u_pc_i_5 \
          dut/u_pc_i_50 \
          dut/u_pc_i_51 \
          dut/u_pc_i_52 \
          dut/u_pc_i_53 \
          dut/u_pc_i_54 \
          dut/u_pc_i_55 \
          dut/u_pc_i_56 \
          dut/u_pc_i_57 \
          dut/u_pc_i_58 \
          dut/u_pc_i_59 \
          dut/u_pc_i_6 \
          dut/u_pc_i_60 \
          dut/u_pc_i_61 \
          dut/u_pc_i_62 \
          dut/u_pc_i_63 \
          dut/u_pc_i_64 \
          dut/u_pc_i_65 \
          dut/u_pc_i_66 \
          dut/u_pc_i_67 \
          dut/u_pc_i_68 \
          dut/u_pc_i_69 \
          dut/u_pc_i_7 \
          dut/u_pc_i_70 \
          dut/u_pc_i_71 \
          dut/u_pc_i_72 \
          dut/u_pc_i_73 \
          dut/u_pc_i_74 \
          dut/u_pc_i_75 \
          dut/u_pc_i_76 \
          dut/u_pc_i_77 \
          dut/u_pc_i_78 \
          dut/u_pc_i_79 \
          dut/u_pc_i_8 \
          dut/u_pc_i_80 \
          dut/u_pc_i_81 \
          dut/u_pc_i_82 \
          dut/u_pc_i_83 \
          dut/u_pc_i_84 \
          dut/u_pc_i_85 \
          dut/u_pc_i_86 \
          dut/u_pc_i_87 \
          dut/u_pc_i_88 \
          dut/u_pc_i_89 \
          dut/u_pc_i_9 \
          dut/u_pc_i_90 \
          dut/u_pc_i_91 \
          dut/u_pc_i_92 \
          dut/u_pc_i_93 \
          dut/u_pc_i_94 \
          dut/u_pc_i_95 \
          dut/u_pc_i_96 \
          dut/u_pc_i_97 \
          dut/u_pc_i_98 \
          dut/u_pc_i_99 \
          dut/u_register_file_i_1 \
          dut/u_register_file_i_10 \
          dut/u_register_file_i_11 \
          dut/u_register_file_i_12 \
          dut/u_register_file_i_13 \
          dut/u_register_file_i_14 \
          dut/u_register_file_i_15 \
          dut/u_register_file_i_16 \
          dut/u_register_file_i_17 \
          dut/u_register_file_i_18 \
          dut/u_register_file_i_19 \
          dut/u_register_file_i_2 \
          dut/u_register_file_i_20 \
          dut/u_register_file_i_21 \
          dut/u_register_file_i_22 \
          dut/u_register_file_i_23 \
          dut/u_register_file_i_24 \
          dut/u_register_file_i_25 \
          dut/u_register_file_i_26 \
          dut/u_register_file_i_27 \
          dut/u_register_file_i_28 \
          dut/u_register_file_i_29 \
          dut/u_register_file_i_3 \
          dut/u_register_file_i_30 \
          dut/u_register_file_i_31 \
          dut/u_register_file_i_32 \
          dut/u_register_file_i_33 \
          dut/u_register_file_i_34 \
          dut/u_register_file_i_35 \
          dut/u_register_file_i_36 \
          dut/u_register_file_i_37 \
          dut/u_register_file_i_38 \
          dut/u_register_file_i_39 \
          dut/u_register_file_i_4 \
          dut/u_register_file_i_40 \
          dut/u_register_file_i_41 \
          dut/u_register_file_i_42 \
          dut/u_register_file_i_43 \
          dut/u_register_file_i_44 \
          dut/u_register_file_i_45 \
          dut/u_register_file_i_46 \
          dut/u_register_file_i_47 \
          dut/u_register_file_i_48 \
          dut/u_register_file_i_49 \
          dut/u_register_file_i_5 \
          dut/u_register_file_i_50 \
          dut/u_register_file_i_51 \
          dut/u_register_file_i_52 \
          dut/u_register_file_i_53 \
          dut/u_register_file_i_54 \
          dut/u_register_file_i_55 \
          dut/u_register_file_i_56 \
          dut/u_register_file_i_57 \
          dut/u_register_file_i_58 \
          dut/u_register_file_i_59 \
          dut/u_register_file_i_6 \
          dut/u_register_file_i_60 \
          dut/u_register_file_i_61 \
          dut/u_register_file_i_62 \
          dut/u_register_file_i_63 \
          dut/u_register_file_i_64 \
          dut/u_register_file_i_65 \
          dut/u_register_file_i_66 \
          dut/u_register_file_i_67 \
          dut/u_register_file_i_68 \
          dut/u_register_file_i_69 \
          dut/u_register_file_i_7 \
          dut/u_register_file_i_70 \
          dut/u_register_file_i_71 \
          dut/u_register_file_i_72 \
          dut/u_register_file_i_73 \
          dut/u_register_file_i_74 \
          dut/u_register_file_i_75 \
          dut/u_register_file_i_76 \
          dut/u_register_file_i_77 \
          dut/u_register_file_i_78 \
          dut/u_register_file_i_79 \
          dut/u_register_file_i_8 \
          dut/u_register_file_i_80 \
          dut/u_register_file_i_81 \
          dut/u_register_file_i_82 \
          dut/u_register_file_i_83 \
          dut/u_register_file_i_9]]
